BugFix: Fix error when generate test coverage xml

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -64,13 +64,13 @@ jobs:
             /d:sonar.token="${SONAR_TOKEN}" \
             /d:sonar.host.url="https://sonarcloud.io" \
             /d:sonar.exclusions="**/appsettings*.json, **/SeedData.cs, **/helm/**, **/Migrations/**" \
-            /d:sonar.cs.opencover.reportsPaths="TestResults/coverage/**/*.xml" \
+            /d:sonar.cs.opencover.reportsPaths="testresults/coverage/*.xml" \
             /d:sonar.secret.exclusions="**/appsettings*.json, **/SeedData.cs, **/helm/**, **/Migrations/**"
 
       - name: Build the project
         shell: bash
         run: |
-          dotnet build MediFlow.sln --no-restore --configuration Release || echo "Build failed, continuing with SonarQube analysis."
+          dotnet build MediFlow.sln --no-incremental --no-restore --configuration Release || echo "Build failed, continuing with SonarQube analysis."
 
       - name: Set up Docker
         uses: docker/setup-docker-action@v4
@@ -85,23 +85,14 @@ jobs:
       - name: Build and start Docker Compose
         run: docker compose -f ./docker-compose.yml -f ./docker-compose.override.yml up -d
 
+      - name: Install dotnet-coverage tool
+        run: |
+          dotnet tool install --global dotnet-coverage
+          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
+
       - name: Run tests and generate coverage report
         shell: bash
-        run: |
-          mkdir -p TestResults/coverage
-          for proj in $(find . -type f -name "*.csproj" | grep -i "test"); do
-            echo "Running tests for $proj"
-            dotnet test "$proj" \
-              --no-restore --configuration Release \
-              /p:CollectCoverage=true \
-              /p:CoverletOutputFormat=cobertura \
-              /p:CoverletOutput=TestResults/coverage/$(basename "$proj" .csproj).cobertura.xml || echo "Test failed for $proj"
-          done
-          
-          ls -R TestResults/coverage
-
-      - name: Debug - List coverage files
-        run: ls -R TestResults/coverage
+        run: dotnet-coverage collect "dotnet test MediFlow.sln" -f xml -o "testresults/coverage/test-coverage.xml"
 
       - name: End SonarQube analysis
         env:
